set $term $HOME/.config/.scripts/shell.sh 
set $term $HOME/.config/.scripts/shell.sh 'ssh clanker.enwi.dev' 
set $menu $HOME/.config/.scripts/launcher.sh # wofi --show drun

# Application shortcuts
bindsym $mod+Return exec $$term
bindsym $mod+Shift+Return exec $$term_rem
bindsym $mod+b exec librewolf
bindsym $mod+c exec mate-calc
bindsym $mod+Shift+Ctrl+l exec $HOME/.config/.scripts/suspend.sh
bindsym $mod+Ctrl+l exec $HOME/.config/.scripts/lock.sh
bindsym $mod+Space exec $menu

bindsym $mod+F1 exec way-displays -s DISABLED "eDP-1"
bindsym $mod+Shift+F1 exec way-displays -d DISABLED "eDP-1"

# XF86 Keys and special keys
bindsym --locked XF86AudioMute exec $HOME/.config/.scripts/pipewire-mute.sh
bindsym --locked XF86AudioRaiseVolume exec $HOME/.config/.scripts/pipewire-volume-raise.sh
bindsym --locked XF86AudioLowerVolume exec $HOME/.config/.scripts/pipewire-volume-lower.sh
bindsym --locked XF86AudioPrev exec $HOME/.config/.scripts/playerctl-prev.sh
bindsym --locked XF86AudioPlay exec $HOME/.config/.scripts/playerctl-play-pause.sh
bindsym --locked XF86AudioNext exec $HOME/.config/.scripts/playerctl-next.sh
bindsym XF86MonBrightnessUp exec $HOME/.config/.scripts/brightness-raise.sh
bindsym XF86MonBrightnessDown exec $HOME/.config/.scripts/brightness-lower.sh
bindsym XF86Calculator exec mate-calc
bindsym F3 exec $HOME/.config/.scripts/screenshot.sh
bindsym Print exec $HOME/.config/.scripts/screenshot.sh

# bindsym F2 exec $HOME/.config/.scripts/flip.sh
# Sway shortcuts
bindsym $mod+q kill
bindsym $mod+Shift+r reload

bindsym $mod+Ctrl+Shift+Space exec swaymsg input type:keyboard xkb_switch_layout next
bindsym $mod+Ctrl+Shift+Return exec cd $HOME/.config/.scripts/theme-toggler && ./theme.sh 
